// Filtr variantlari (chap panel)
export const BRANDS = [
    { value: "gaz", labelKey: "brand_gaz" },
    { value: "kamaz", labelKey: "brand_kamaz" },
    { value: "jac", labelKey: "brand_jac" },
    { value: "daewoo", labelKey: "brand_daewoo" },
    { value: "foton", labelKey: "brand_foton" },
    { value: "dongfeng", labelKey: "brand_dongfeng" },
    { value: "maz", labelKey: "brand_maz" },
];

export const WEIGHTS = [
    { value: "up_to_5_5", labelKey: "weight_up_to_5_5" },
    { value: "up_to_12", labelKey: "weight_up_to_12" },
    { value: "up_to_20", labelKey: "weight_up_to_20" },
    { value: "over_20", labelKey: "weight_over_20" },
];

const katolgData = [
    {
        id: 1,
        titleKey: "katolg_product1_title",
        brand: "gaz",
        weight: "up_to_5_5",
        priceType: "from",
        priceAmount: "352 000₽",
        loadCapacity: "6340",
        image: "/site-media-012.webp",
    },
    {
        id: 2,
        titleKey: "katolg_product1_title",
        brand: "kamaz",
        weight: "up_to_20",
        priceType: "request",
        loadCapacity: "13800",
        image: "/site-media-007.webp",
    },
    {
        id: 3,
        titleKey: "katolg_product1_title",
        brand: "jac",
        weight: "up_to_12",
        priceType: "from",
        priceAmount: "352 000₽",
        loadCapacity: "1580",
        image: "/site-media-008.webp",
    },
    {
        id: 4,
        titleKey: "katolg_product1_title",
        brand: "daewoo",
        weight: "up_to_12",
        priceType: "from",
        priceAmount: "352 000₽",
        image: "/site-media-009.webp",
    },
    {
        id: 5,
        titleKey: "katolg_product1_title",
        brand: "foton",
        weight: "up_to_5_5",
        priceType: "from",
        priceAmount: "352 000₽",
        image: "/site-media-007.webp",
    },
    {
        id: 6,
        titleKey: "katolg_product1_title",
        brand: "dongfeng",
        weight: "over_20",
        priceType: "from",
        priceAmount: "352 000₽",
        image: "/site-media-012.webp",
    },
    {
        id: 7,
        titleKey: "katolg_product1_title",
        brand: "maz",
        weight: "over_20",
        priceType: "request",
        image: "/site-media-007.webp",
    },
    {
        id: 8,
        titleKey: "katolg_product1_title",
        brand: "gaz",
        weight: "up_to_12",
        priceType: "from",
        priceAmount: "352 000₽",
        image: "/site-media-008.webp",
    },
    {
        id: 9,
        titleKey: "katolg_product1_title",
        brand: "kamaz",
        weight: "over_20",
        priceType: "from",
        priceAmount: "352 000₽",
        image: "/site-media-009.webp",
    },
    {
        id: 10,
        titleKey: "katolg_product1_title",
        brand: "jac",
        weight: "up_to_5_5",
        priceType: "from",
        priceAmount: "352 000₽",
        image: "/site-media-007.webp",
    },
];

export default katolgData;